[package]
name = "shuttli-mobile-sdk"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[package.metadata.shuttli]
layer = "mobile-sdk"

[lints]
workspace = true

[dependencies]
shuttli-content.workspace = true
shuttli-model.workspace = true
shuttli-protocol = { path = "../protocol" }
shuttli-identity.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true
rustls.workspace = true
getrandom.workspace = true
