#!/usr/bin/env bash
set -euo pipefail

# Requires the XCFramework and Xcode project generated by build_ios.sh.
repo_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
cd "$repo_dir"
[[ $(uname -s) == Darwin ]] || { echo "iOS packaging requires macOS and Xcode" >&2; exit 1; }
out="$repo_dir/target/mobile-ios"
mkdir -p "$out"
xcodebuild -project apps/ios/Shuttli.xcodeproj -scheme Shuttli \
  -configuration Release -destination 'generic/platform=iOS' -sdk iphoneos \
  -derivedDataPath target/ios-device-derived \
  CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO ARCHS=arm64 ONLY_ACTIVE_ARCH=YES build

python3 - "$repo_dir" <<'PY'
import hashlib
import json
from pathlib import Path
import plistlib
import re
import shutil
import subprocess
import sys
import tempfile
import zipfile

repo = Path(sys.argv[1])
out = repo / "target/mobile-ios"
app = repo / "target/ios-device-derived/Build/Products/Release-iphoneos/Shuttli.app"
info = plistlib.loads((app / "Info.plist").read_bytes())
executable = app / info["CFBundleExecutable"]
architectures = subprocess.check_output(["xcrun", "lipo", "-archs", str(executable)], text=True).split()
build_info = subprocess.check_output(["xcrun", "vtool", "-show-build", str(executable)], text=True)
if architectures != ["arm64"] or not re.search(r"^\s*platform IOS\s*$", build_info, re.MULTILINE):
    raise SystemExit("Expected an arm64 iPhone device executable, not a simulator build")
if info.get("CFBundleSupportedPlatforms") != ["iPhoneOS"]:
    raise SystemExit("Unexpected supported platforms")
if not isinstance(info.get("UILaunchScreen"), dict):
    raise SystemExit("Missing launch screen; iPhone may use a letterboxed compatibility layout")
if (app / "embedded.mobileprovision").exists() or (app / "_CodeSignature").exists():
    raise SystemExit("Do not publish device provisioning profiles or signing assets")

ipa = out / "shuttli-device-unsigned.ipa"
with tempfile.TemporaryDirectory(dir=out) as staging:
    payload = Path(staging) / "Payload"
    payload.mkdir()
    shutil.copytree(app, payload / app.name, symlinks=True)
    subprocess.run(["ditto", "-c", "-k", "--keepParent", str(payload), str(ipa)], check=True)
with zipfile.ZipFile(ipa) as archive:
    if archive.testzip() is not None:
        raise SystemExit("Corrupt IPA archive")
    names = archive.namelist()
    if any(not name.startswith("Payload/Shuttli.app/") for name in names if not name.endswith("/")):
        raise SystemExit("Unexpected IPA payload")
    if "Payload/Shuttli.app/Info.plist" not in names:
        raise SystemExit("Missing application manifest")

manifest = {
    "commit": subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=repo, text=True).strip(),
    "sdk_api": 6,
    "wire_version": 3,
    "platform": "iPhoneOS",
    "architectures": architectures,
    "bundle_id": info["CFBundleIdentifier"],
    "version": info["CFBundleShortVersionString"],
    "build": info["CFBundleVersion"],
    "minimum_os": info["MinimumOSVersion"],
    "signing": "unsigned; sign for your device before installation",
    "xcode": subprocess.check_output(["xcodebuild", "-version"], text=True).strip(),
    "files": {
        ipa.name: {"sha256": hashlib.sha256(ipa.read_bytes()).hexdigest(), "bytes": ipa.stat().st_size},
        "Cargo.lock": {"sha256": hashlib.sha256((repo / "Cargo.lock").read_bytes()).hexdigest()},
    },
}
(out / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
print(f"Created {ipa.name}: {manifest['files'][ipa.name]['bytes']} bytes, iOS {manifest['minimum_os']}+")
PY
