[package]
name = "shuttli-identity"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[package.metadata.shuttli]
layer = "identity"

[lints]
workspace = true

[dependencies]
shuttli-model.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
rustls.workspace = true
rcgen.workspace = true
x509-parser.workspace = true
