#!/usr/bin/env python3
"""Regenerate stdlib-only tray pixmaps from approved PNGs (requires Pillow)."""
import base64
from pathlib import Path
import zlib
from PIL import Image

ROOT = Path(__file__).resolve().parents[1] / 'crates/native-ui'
art = {}
for ident, stem in enumerate(['send-on-receive-on', 'send-on-receive-off',
                             'send-off-receive-on', 'send-off-receive-off',
                             'service-unavailable'], 1):
    for size in (16, 24, 32):
        path = ROOT / f'assets/tray/tray-{stem}-on-dark-{size}.png'
        with Image.open(path) as image:
            rgba = image.convert('RGBA')
            assert rgba.size == (size, size)
            raw = rgba.tobytes()
        argb = bytes(value for i in range(0, len(raw), 4)
                     for value in (raw[i+3], raw[i], raw[i+1], raw[i+2]))
        art[(ident, size)] = base64.b85encode(zlib.compress(argb, 9)).decode()
(ROOT / 'linux/tray_icons.py').write_text('''"""Generated by tools/render_tray_icons.py from assets/tray.

Approved Linked sheets artwork, network ARGB for dark-panel fallback pixmaps.
Only 15 small immutable decoded images are cached; no GTK/image library at runtime.
"""
import base64
from functools import lru_cache
import zlib

ART = ''' + repr(art) + '''

@lru_cache(maxsize=15)
def pixels(ident, size):
    return zlib.decompress(base64.b85decode(ART[(ident, size)]))
''', encoding='utf-8')
